name: contacts_app_isidore
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  form_validator: ^1.0.4
  get_it: ^7.2.0
  google_fonts: ^4.0.4
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1


flutter:
  uses-material-design: true
